name: Build component
# This workflow is triggered on pushes to the repository and for pull requests.
on: [push, pull_request]
jobs:
  build:
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources from master branch
      uses: actions/checkout@v2-beta

    - name: Checkout additional sources from product repository
      uses: actions/checkout@v2-beta
      with:
        repository: Guite/MostProduct
        token: ${{ secrets.ACCESS_MOST_PRODUCT }}
        path: MostProduct

    # GITHUB_WORKSPACE contains "/github/workspace"
    - run: ln -s ${{ GITHUB_WORKSPACE }}/MostProduct /github/MostProduct
    - run: ls -l ../MostProduct/releng

    # see https://github.com/xlui/action-maven-cli
    - name: Call Maven
      uses: xlui/action-maven-cli/jdk11@master
      with:
        args: clean verify
