name: Build component
# This workflow is triggered on pushes to the repository and for pull requests.
on: [push, pull_request]
jobs:
  build:
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources from master branch
      uses: actions/checkout@v1
      with:
        ref: master

    # see https://github.com/fregante/setup-git-token
    - name: Setup Git token
      uses: fregante/setup-git-token@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout additional sources from product repository
      run: |
        mkdir -p MostProduct && cd MostProduct
        git clone https://github.com/Guite/MostProduct.git
        cd ..

    # see https://github.com/xlui/action-maven-cli
    - name: Call Maven
      uses: xlui/action-maven-cli/jdk11@master
      with:
        args: clean verify
